[build]
  command = "npm run production"
  publish = "dist"
  
[[redirects]]
  from = "/pages/projects"
  to = "/work"

[[redirects]]
  from = "/pages/work"
  to = "/work"

[[redirects]]
  from = "/pages/contact"
  to = "/contact"

[[redirects]]
  from = "/pages/speaking"
  to = "/speaking"

[[redirects]]
  from = "/pages/writing"
  to = "/writing"

# Proxying Plausible through Netlify
# @see https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/masked-source/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/masked-source/api/event"
  to = "https://plausible.io/api/event"
  status = 200